language: ruby
rvm: 2.5.2
dist: xenial
group: edge

cache:
  bundler: true
  directories:
  - ${HOME}/perl5
  - ${HOME}/.cache

services:
- redis

addons:
  postgresql: 9.6

env:
  global:
  - DATABASE_URL='postgres://localhost:5432/job_board_test'
  - RUBYOPT=-W0
  matrix:
  - INTEGRATION_SPECS='1' COVERAGE='1'
  - INTEGRATION_SPECS='0'

before_install:
- script/install-sqitch
- eval "$(perl -I ~/perl5/lib/perl5/ '-Mlocal::lib')"

before_script:
- createdb job_board_test
- sqitch deploy
- sqitch verify
